# auto: false
markdown: kramdown
permalink: /:categories/:title
rdiscount extensions: [smart]
# highlighter: pygments
lsi: false

paginate: 50
paginate_path: "archives/page:num"

#pygments:
#  tab_size: 2
  
